version: "3"

  loki:
    name: loki

# https://grafana.com/docs/loki/latest/installation/docker/
# https://github.com/gliderlabs/logspout
# https://grafana.com/docs/loki/latest/clients/promtail/

# if you are going to send syslogs from an external source run the following:
# make enable-override promtail-syslog

services:
  prometheus-loki:
    image: grafana/loki:${LOKI_DOCKER_TAG:-latest}
    container_name: ${LOKI_CONTAINER_NAME:-prometheus-loki}
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./etc/loki:/etc/loki
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  logspout:
    image: gliderlabs/logspout:${LOGSPOUT_DOCKER_TAG:-latest}
    container_name: logspout
    restart: unless-stopped
    networks:
      - traefik
    command: syslog+tcp://promtail:1514
    networks:
      - loki
    depends_on:
      - promtail
    environment:
      - SYSLOG_HOSTNAME={{.ContainerName}}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  promtail:
    image: grafana/promtail:${PROMTAIL_DOCKER_TAG:-latest}
    container_name: promtail
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /var/log:/var/log
      - ./etc/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  