networks:
  traefik:
    external: true

# description: Manages alerts from prometheus monitoring
# https://github.com/prometheus/alertmanager

volumes:
  prometheus:
    name: onramp_prometheus
    external: true

services:
  prometheus-alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_DOCKER_TAG:-latest}
    env_file:
      - ./services-enabled/prometheus-alertmanager.env
    container_name: ${ALERTMANAGER_CONTAINER_NAME:-prometheus-alertmanager}
    restart: unless-stopped
    networks:
      - traefik
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --log.level=debug
    # ports:
    #   - 9093:9093
    volumes:
      - ./etc/prometheus/conf:/etc/alertmanager:rw
      - prometheus:/alertmanager:rw
    labels:
      - joyride.host.name=${ALERTMANAGER_HOST_NAME:-alertmanager}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.alertmanager.rule=Host(`${ALERTMANAGER_HOST_NAME:-alertmanager}.${HOST_DOMAIN}`)
      - traefik.http.routers.alertmanager.entrypoints=websecure
      - traefik.http.services.alertmanager.loadbalancer.server.port=9093
      - com.centurylinklabs.watchtower.enable=${ALERTMANAGER_WATCHTOWER_ENABLED:-true}
