# description: Exposes hardware and os metrics to prometheus
# https://github.com/prometheus/node_exporter
# Please see Makefile install-node-exporter: to install node-export directly on the host
# by running: 'make install-node-exporter' as an alternative to using this container

services:
  nodeexporter:
    image: prom/node-exporter:${NODE_EXPORTER_DOCKER_TAG:-latest}
    env_file:
      - ./services-enabled/prometheus-node-exporter.env
    container_name: prometheus-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
