http:
  routers:

    pihole:
      entryPoints:
        - websecure
      rule: "Host(`{{env "PIHOLE_HOST_NAME"}}.{{env "HOST_DOMAIN"}}`)"
      middlewares:
        - default-headers
        - pihole-redirect 
      tls: {}
      service: pihole

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://{{env "PIHOLE_ADDRESS"}}:80"
        passHostHeader: true

  middlewares:
    pihole-redirect:
      redirectRegex:
        regex: "^https?://{{env "PIHOLE_HOST_NAME"}}.{{env "HOST_DOMAIN"}}/$"
        replacement: "https://{{env "PIHOLE_HOST_NAME"}}.{{env "HOST_DOMAIN"}}/admin/"
